name: add_to_app_sample_repository

repository: https://github.com/kosukesaigusa/add-to-app-sample

packages:
  - flutter/packages/**

sdkPath: .fvm/versions/3.22.3

command:
  bootstrap:
    environment:
      sdk: ">=3.0.0 <4.0.0"
      flutter: ">=3.0.0 <4.0.0"

    dependencies:
      flutter_hooks: ^0.20.5
      freezed_annotation: ^2.4.1
      gap: ^3.0.1
      hooks_riverpod: ^2.5.1
      meta: ^1.11.0
      riverpod_annotation: ^2.3.5
      uuid: ^4.4.0
    
    dev_dependencies:
      build_runner: ^2.4.9
      freezed: ^2.5.2
      mockito: ^5.4.4
      riverpod_generator: ^2.4.0

scripts:
  clean:
    run: melos exec -- "flutter clean"

  pg:
    run: melos exec -- "flutter pub get"

  clpg:
    run: melos exec -- "flutter clean && flutter pub get"

  build:
    run: melos exec -c 1 -- "dart pub run build_runner build -d"
